CI: try to fix status checks [ci skip]

diff --git a/.github/workflows/github-actions.yml b/.github/workflows/github-actions.yml
--- a/.github/workflows/github-actions.yml
+++ b/.github/workflows/github-actions.yml
@@ -265,11 +265,20 @@ jobs:
   status-checks:
     name: status-checks
     needs: [codecov, generation]
+    permissions:
+      contents: none
+    if: always()
     runs-on: ubuntu-latest
     timeout-minutes: 5
     steps:
       - name: Validation Status checks
-        run: echo 'Configuration for Status checks that are required'
+        run: |
+          echo 'Configuration for Status checks that are required'
+          echo '${{ toJSON(needs) }}'
+          if [[ (('skipped' == '${{ needs.codecov.result }}') || ('success' == '${{ needs.codecov.result }}')) && (('skipped' == '${{ needs.generation.result }}') || ('success' == '${{ needs.generation.result }}')) ]]; then
+            exit 0
+          fi
+          exit 1
 
   #--------------------------------------------------
   # Dependabot auto merge PR
